<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 5. Over-Population – German Marxists in Translation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7e462b68550b93e95c1625bbce22e1a6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../assets/parallel.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/vorwort1.html">Text</a></li><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/ab3-kap1.html">Part III. Wages and the Income of Capital</a></li><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/ab3-kap5.html">Chapter 5. Over-Population</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">The Economic Doctrines of Karl Marx</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Karl Marx’ Oekonomische Lehren / The Economic Doctrines of Karl Marx</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Text</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/vorwort1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the First Edition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/vorwort4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the Fourth Edition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/vorwort8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the Eighth Edition</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Part I. Commodity, Money, Capital</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab1-kap1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1. The Commodity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap1.html#the-character-of-commodity-production" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The Character of Commodity Production</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap1.html#value" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap1.html#the-exchange-value" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Exchange Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap1.html#the-exchange-of-commodities" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. The Exchange of Commodities</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab1-kap2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2. Money</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap2.html#the-price" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The Price</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap2.html#sale-and-purchase" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Sale and Purchase</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap2.html#the-circulation-of-money" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Circulation of Money</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap2.html#coin.-paper-money" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Coin. Paper Money</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap2.html#further-functions-of-money" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Further Functions of Money</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab1-kap3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3. The Transformation of Money into Capital</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap3.html#what-is-capital" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. What is Capital?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap3.html#the-source-of-surplus-value" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Source of Surplus Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab1-kap3.html#labour-power-as-a-commodity" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Labour-power as a Commodity</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Part II. Surplus Value</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1. The Process of Production</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2. The Role of Capital in the Formation of Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3. The Degree of Exploitation of Labour-Power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4. Surplus Value and Profit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 5. The Working Day</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 6. The Surplus Value of the Small Master and the Surplus Value of the Capitalist</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 7. Relative Surplus Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 8. Co-operation</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab2-kap09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 9. Division of Labour and Manufacture</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap09.html#the-twofold-origin-of-manufacture.-its-elements-the-detail-worker-and-his-tool" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The Twofold Origin of Manufacture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap09.html#the-two-basic-forms-in-manufacture" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Two Basic Forms in Manufacture</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab2-kap10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 10. Machinery and Large-Scale Industry</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-development-of-machinery" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The Development of Machinery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-transfer-of-value-from-the-machinery-to-the-product" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Transfer of Value from the Machinery to the Product</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-immediate-effects-of-machine-based-operation-on-the-workers" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Immediate Effects of Machine-based Operation on the Workers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-machine-as-the-workers-educator" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. The Machine as the Worker’s “Educator”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-machine-and-the-labour-market" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. The Machine and the Labour Market</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab2-kap10.html#the-machine-as-a-revolutionary-agent" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. The Machine as a Revolutionary Agent</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III. Wages and the Income of Capital</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab3-kap1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 1. The Wage of Labour</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap1.html#changes-in-the-magnitude-of-the-price-of-labour-power-and-surplus-value" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Changes in the Magnitude of the Price of Labour-Power and Surplus Value</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap1.html#the-transformation-of-the-price-of-labour-power-into-wages" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Transformation of the Price of Labour-Power into Wages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap1.html#time-wages" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Time-Wages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap1.html#piece-wages" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Piece Wages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap1.html#national-differences-in-wages" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. National Differences in Wages</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2. The Income of Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3. Simple Reproduction</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab3-kap4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4. The Transformation of Surplus Value into Capital</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap4.html#how-surplus-value-becomes-capital" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. How Surplus Value Becomes Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap4.html#the-abstinence-of-the-capitalist" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Abstinence of the Capitalist</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap4.html#the-abstinence-of-the-worker-and-other-circumstances-that-influence-the-beginning-of-accumulation" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. The Abstinence of the Worker</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../oekonomische-lehren/chapters/ab3-kap5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Chapter 5. Over-Population</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap5.html#the-iron-law-of-wages" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The “Iron Law of Wages”</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap5.html#the-industrial-reserve-army" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. The Industrial Reserve Army</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 6. The Dawn of the Capitalist Mode of Production</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oekonomische-lehren/chapters/ab3-kap7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 7. The Close of the Capitalist Mode of Production</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#notes-anmerkungen" id="toc-notes-anmerkungen" class="nav-link active" data-scroll-target="#notes-anmerkungen">Notes / Anmerkungen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/vorwort1.html">Text</a></li><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/ab3-kap1.html">Part III. Wages and the Income of Capital</a></li><li class="breadcrumb-item"><a href="../../oekonomische-lehren/chapters/ab3-kap5.html">Chapter 5. Over-Population</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Chapter 5. Over-Population</h1>
<p class="subtitle lead">5. Kapitel. Die Uebervölkerung</p>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<section id="the-iron-law-of-wages" class="level5">
<h5 class="anchored" data-anchor-id="the-iron-law-of-wages">1. The “Iron Law of Wages”</h5>
<p class="de-subtitle">
</p><ol type="1">
<li>Das „eherne Lohngesetz“
<p></p></li>
</ol>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Die Malthusianer erklären bekanntlich, daß die Arbeiter in Folge ihrer „leichtsinnigen Gewohnheiten“ sich rascher vermehren, als die Masse der verfügbaren Lebensmittel, oder um genauer zu sprechen, das variable Kapital, anwachsen kann. Auf diese Weise komme es, daß eine Uebervölkerung eintrete, daß mehr Arbeiter sich den Kapitalisten anböten, als diese beschäftigen könnten, daß die verfügbaren Lebensmittel nicht für alle vorhandenen Arbeiter hinreichten, daß also, so lange die Vermehrung der Arbeiter nicht eingeschränkt werde, Arbeitslosigkeit und Hunger und alles daraus folgende Laster und Elend naturnothwendig das Loos mindestens eines Theils der Arbeiterklasse seien.</p>
</div>
<div class="parallel-col-en">
<p class="fst">The Malthusians declare, as is well known, that the workers, as a consequence of their "frivolous habits," multiply more rapidly than the mass of available means of subsistence can grow, or, to speak more precisely, than the variable capital can grow. In this way it comes about that an overpopulation sets in, that more workers offer themselves to the capitalists than the latter can employ, that the available means of subsistence do not suffice for all the workers who exist, and that therefore, so long as the multiplication of the workers is not restricted, unemployment and hunger and all the vice and misery that follow from them are by natural necessity the lot of at least a part of the working class.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>So die Malthusianer. Untersuchen wir nun an der Hand von Marx, wie die Wechselbeziehungen zwischen dem Wachsthum des Kapitals und der Vermehrung der Arbeiterklasse sich in Wirklichkeit gestalten.</p>
</div>
<div class="parallel-col-en">
<p>So say the Malthusians. Let us now examine, with the guidance of Marx, how the reciprocal relations between the growth of capital and the multiplication of the working class actually shape themselves in reality.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="quoteb">„Der wichtigste Faktor bei dieser Untersuchung,“ sagt Marx (S.&nbsp;628 der 3., S.&nbsp;576 der 4. Aufl. des <strong>Kapital.</strong> In der 1. und 2. Aufl. fehlt diese Auseinandersetzung), „ist die <em>Zusammensetzung</em> des Kapitals und die Veränderungen, die sie im Verlaufe des Akkumulationsprozesses durchmacht.“</p>
</div>
<div class="parallel-col-en">
<p class="quoteb">"The most important factor in this investigation," says Marx (p. 628 of the 3rd, p. 576 of the 4th edition of <strong>Capital.</strong> This discussion is missing in the 1st and 2nd editions), "is the <em>composition</em> of capital and the changes which it undergoes in the course of the process of accumulation."</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="quote">„Die Zusammensetzung des Kapitals ist in zweifachem Sinn zu fassen. Nach der Seite des Werths bestimmt sie sich durch das Verhältniß, worin es sich theilt in konstantes Kapital oder Werth der Produktionsmittel und variables Kapital oder Werth der Arbeitskraft, Gesammtsumme der Arbeitslöhne. Nach der Seite des Stoffs, wie er im Produktionsprozeß fungirt, theilt sich jedes Kapital in Produktionsmittel und lebendige Arbeitskraft; diese Zusammensetzung bestimmt sich durch das Verhältniß zwischen der Masse der angewandten Produktionsmittel einerseits und der zu ihrer Anwendung erforderlichen Arbeitsmenge andererseits. Ich nenne die erstere die <em>Werthzusammensetzung,</em> die zweite die <em>technische Zusammensetzung</em> des Kapitals. Zwischen beiden besteht enge Wechselbeziehung. Um diese auszudrücken, nenne ich die Werthzusammensetzung des Kapitals, insofern sie durch seine technische Zusammensetzung bedingt wird und deren Aenderungen widerspiegelt: <em>die organische Zusammensetzung</em> des Kapitals. Wo von der Zusammensetzung des Kapitals kurzweg die Rede, ist stets seine organische Zusammensetzung zu verstehen.“</p>
</div>
<div class="parallel-col-en">
<p class="quote">"The composition of capital is to be understood in a twofold sense. On the side of value, it is determined by the proportion in which it is divided into constant capital or value of the means of production and variable capital or value of the labour-power, the total sum of the wages. On the side of the material, as it functions in the process of production, every capital is divided into means of production and living labour-power; this composition is determined by the relation between the mass of the means of production employed on the one hand and the amount of labour required for their employment on the other. I call the former the <em>value-composition,</em> the latter the <em>technical composition</em> of capital. Between the two there exists a close reciprocal relation. In order to express this, I call the value-composition of capital, in so far as it is determined by its technical composition and reflects the changes of the latter: <em>the organic composition</em> of capital. Wherever the composition of capital is spoken of without further qualification, its organic composition is always to be understood."</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Diese ist bei den verschiedenen Einzelkapitalien verschieden. Wir nehmen im Folgenden die <em>durchschnittliche</em> Zusammensetzung des gesellschaftlichen Kapitals eines Landes an.</p>
</div>
<div class="parallel-col-en">
<p class="fst">This composition differs among the various individual capitals. In what follows we assume the <em>average</em> composition of the social capital of a country.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Gehen wir nach diesen Vorbemerkungen an unsere Untersuchung.</p>
</div>
<div class="parallel-col-en">
<p>After these preliminary remarks let us proceed to our investigation.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Vor Allem betrachten wir den einfachsten Fall: die Akkumulation gehe vor sich <em>ohne Veränderung</em> in der Zusammensetzung des Kapitals, das heißt, ein bestimmtes Maß von Produktionsmitteln erheische stets dieselbe Masse Arbeitskraft, um in Bewegung gesetzt zu werden. Nehmen wir zur Veranschaulichung ein Kapital von 100.000 Mark an, das zu drei Viertheilen aus konstantem, einem Viertheil aus variablem Kapital bestehe. Werden von dem Mehrwerth 20.000 Mark zum ursprünglichen Kapital geschlagen, so wird das Zuschußkapital unter unserer Voraussetzung in demselben Verhältniß getheilt sein, wie jenes; das Gesammtkapital wird jetzt aus 90.000 Mark konstantem und 30.000 Mark variablem Kapital bestehen; das letztere ist in demselben Verhältniß gewachsen, wie das erstere, um 20 Prozent. Soll aber das neue zuschüssige Kapital sich verwerthen, so bedarf es zuschüssiger Arbeitskraft. Der zu akkumulirende Mehrwerth von 20.000 Mk. kann in unserem Fall nur Kapital werden, wenn die Zahl der ihm zur Verfügung stehenden Lohnarbeiter sich um 20 Prozent vermehrt.</p>
</div>
<div class="parallel-col-en">
<p>Above all we consider the simplest case: let accumulation proceed <em>without change</em> in the composition of capital, that is to say, a definite quantity of means of production always requires the same mass of labour-power in order to be set in motion. Let us assume, for illustration, a capital of 100,000 marks, consisting of three-quarters constant and one-quarter variable capital. If 20,000 marks of the surplus value are added to the original capital, then, under our assumption, the additional capital will be divided in the same proportion as the former; the total capital will now consist of 90,000 marks constant and 30,000 marks variable capital; the latter has grown in the same proportion as the former, by 20 per cent. But if the new additional capital is to valorise itself, it requires additional labour-power. The surplus value of 20,000 marks to be accumulated can, in our case, only become capital if the number of wage labourers at its disposal increases by 20 per cent.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Vermehren sich die Lohnarbeiter bei gleichbleibender Zusammensetzung des Kapitals nicht so rasch, wie dieses, dann wächst die Nachfrage nach Arbeitern schneller als deren Angebot, und der Lohn steigt.</p>
</div>
<div class="parallel-col-en">
<p>If, with the composition of capital remaining the same, the wage labourers do not multiply as rapidly as it does, then the demand for workers grows faster than their supply, and wages rise.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Diesen Fall haben die Malthusiauer im Auge, wenn sie zur „Lösung der sozialen Frage“ die Einschränkung der Vermehrung der Arbeiter empfehlen. Sie übersehen dabei zunächst, daß das Kapitalverhältniß, das Verhältniß zwischen Kapitalisten und Lohnarbeitern, durch das Steigen des Lohnes nicht aufgehoben wird. Die Akkumulation des Kapitals bedeutet Reproduktion des Kapitalverhältnisses auf <em>erweiterter Stufenleiter,</em> bedeutet das Wachsthum der Kapitalien und der Masse des Mehrwerthes, der unbezahlten Arbeit, auf der einen, <em>Vermehrung des Proletariats</em> auf der anderen Seite.</p>
</div>
<div class="parallel-col-en">
<p>This is the case the Malthusians have in mind when, for the "solution of the social question," they recommend the restriction of the multiplication of the workers. In doing so, they overlook, first of all, that the capital relation, the relation between capitalists and wage labourers, is not abolished by the rise of wages. The accumulation of capital means the reproduction of the capital relation on an <em>enlarged scale,</em> means the growth of capitals and of the mass of surplus value, of unpaid labour, on the one side, and the <em>multiplication of the proletariat</em> on the other.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Selbst wenn die Akkumulation des Kapitals den Preis der Arbeit steigert, so kann das nicht geschehen ohne gleichzeitige Vermehrung des Proletariats, es kann nicht geschehen ohne Erweiterung des Herrschaftsgebietes des Kapitals.</p>
</div>
<div class="parallel-col-en">
<p>Even if the accumulation of capital raises the price of labour, this cannot happen without a simultaneous multiplication of the proletariat; it cannot happen without an extension of the domain of the rule of capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Der Lohn kann aber nie so hoch steigen, daß er den Mehrwerth selbst gefährdet. Die Nachfrage nach Arbeitskraft wird unter der kapitalistischen Produktionsweise hervorgerufen durch das Bedürfniß des Kapitals nach Selbstverwerthung, nach der Produktion von Mehrwerth. Das Kapital wird daher nie die Arbeitskraft zu einem Preise kaufen, der die Produktion von Mehrwerth ausschließt.</p>
</div>
<div class="parallel-col-en">
<p>Wages, however, can never rise so high as to endanger surplus value itself. Under the capitalist mode of production the demand for labour-power is called forth by the need of capital for its self-valorisation, for the production of surplus value. Capital will therefore never buy labour-power at a price that excludes the production of surplus value.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Steigt der Arbeitslohn in Folge der Akkumulation des Kapitals, dann ist zweierlei möglich: entweder der Fortschritt der Akkumulation wird durch das Steigen des Preises der Arbeit nicht gestört – wenn auch die Rate des Mehrwerthes sinkt, so kann doch gleichzeitig in Folge der Akkumulation die Masse des Mehrwerthes steigen. „In diesem Falle ist es augenscheinlich, daß eine Verminderung der unbezahlten Arbeit die Ausdehnung der Kapitalherrschaft keineswegs beeinträchtigt.“ Oder die Akkumulation erschlafft, „weil der Stachel des Gewinns abstumpft.“ Die Akkumulation nimmt ab, damit aber auch die Ursache, welche den Arbeitslohn in die Höhe trieb. Dieser fällt in Folge dessen, bis er den dem Verwerthungsbedürfniß des Kapitals genügenden Stand erreicht. „Der Mechanismus der kapitalistischen Produktionsweise beseitigt also selbst die Hindernisse, die er schafft.“</p>
</div>
<div class="parallel-col-en">
<p>If wages rise as a consequence of the accumulation of capital, then two things are possible: either the progress of accumulation is not disturbed by the rise in the price of labour – even if the rate of surplus value falls, the mass of surplus value may nevertheless rise at the same time as a consequence of accumulation. "In this case it is evident that a diminution of the unpaid labour in no way interferes with the extension of the domination of capital." Or accumulation slackens, "because the stimulus of gain is blunted." Accumulation decreases, but with it also the cause which drove wages upward. Wages consequently fall until they reach the level that satisfies the valorisation-need of capital. "The mechanism of the capitalist mode of production thus itself removes the obstacles which it creates."</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wir sehen da eine eigenthümliche Wechselwirkung zwischen bezahlter und unbezahlter Arbeit.</p>
</div>
<div class="parallel-col-en">
<p>We see here a peculiar reciprocal action between paid and unpaid labour.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="quoteb">„Wächst die Menge der von der Arbeiterklasse gelieferten und von der Kapitalistenklasse akkumulirten unbezahlten Arbeit rasch genug, um nur durch einen außergewöhnlichen Zuschuß bezahlter Arbeit sich in Kapital verwandeln zu können, so steigt der Lohn, und alles Andere gleichgesetzt, nimmt die unbezahlte Arbeit im Verhältniß ab. Sobald aber diese Abnahme den Punkt berührt, wo die das Kapital ernährende Mehrarbeit nicht mehr in normaler Menge angeboten wird, so tritt eine Reaktion ein: ein geringerer Theil der Revenue wird kapitalisirt, die Akkumulation erlahmt und die steigende Lohnbewegung empfängt einen Gegenschlag. Die Erhöhung des Arbeitspreises bleibt also eingebannt in Grenzen, die die Grundlagen des kapitalistischen Systems nicht nur unangetastet lassen, sondern auch seine Reproduktion auf wachsender Stufenleiter sichern.“</p>
</div>
<div class="parallel-col-en">
<p class="quoteb">"If the quantity of unpaid labour supplied by the working class and accumulated by the capitalist class grows rapidly enough to be able to transform itself into capital only through an extraordinary addition of paid labour, then wages rise, and, all other things being equal, the unpaid labour diminishes in proportion. But as soon as this diminution touches the point where the surplus labour that nourishes capital is no longer supplied in normal quantity, a reaction sets in: a smaller part of the revenue is capitalised, accumulation flags, and the rising movement of wages receives a counter-blow. The rise in the price of labour therefore remains confined within limits which not only leave the foundations of the capitalist system untouched, but also secure its reproduction on a growing scale."</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Die Schwankungen in der Akkumulation des Kapitals, die den Lohn innerhalb gewisser Grenzen festhalten, erscheinen den bürgerlichen Oekonomen als Schwankungen in der Menge der sich anbietenden Lohnarbeiter. Sie unterliegen da einer Täuschung, ähnlich der von Leuten, die glauben, die Sonne bewege sich um die Erde und diese stehe still. <a href="#ab3-kap5-n1" id="ab3-kap5-f1" name="ab3-kap5-f1">[1]</a> Verlangsamt sich die Akkumulation des Kapitals, so erweckt das den Anschein, als wachse die Arbeiterbevölkerung rascher als sonst; nimmt jene ein schnelleres Tempo an, so erscheint es, als nehme die Arbeiterbevölkerung ab, oder wachse langsamer als sonst. In der That wird, wie den meisten unserer Leser bekannt sein dürfte, die Erscheinung, daß der Lohn auf und nieder schwankt, ohne je gewisse Grenzen überschreiten zu können, das sogenannte „eherne Lohngesetz,“ damit begründet, daß, wenn der Lohn steigt, die Arbeiterbevölkerung sich in Folge dessen rasch vermehrt und das vermehrte Angebt den Lohn senkt, indeß ein Sinken des Lohnes größeres Elend und größere Sterblichkeit in der Arbeiterklasse zur Folge hat, welche das Angebot von Arbeitskraft verringert und so den Lohn wieder hebt.</p>
</div>
<div class="parallel-col-en">
<p class="fst">The fluctuations in the accumulation of capital, which hold wages within certain limits, appear to the bourgeois economists as fluctuations in the number of wage labourers offering themselves. They are here subject to a delusion, similar to that of people who believe that the sun moves around the earth and that the latter stands still. <a href="#ab3-kap5-n1" id="ab3-kap5-f1" name="ab3-kap5-f1">[1]</a> If the accumulation of capital slows down, this creates the appearance that the working population is growing more rapidly than usual; if the accumulation takes on a faster tempo, it appears as though the working population is decreasing, or growing more slowly than usual. In fact, as will probably be familiar to most of our readers, the phenomenon that wages fluctuate up and down without ever being able to overstep certain limits, the so-called "iron law of wages," is explained on the ground that, when wages rise, the working population as a result increases rapidly and the increased supply lowers wages, while a fall in wages results in greater misery and greater mortality in the working class, which diminishes the supply of labour-power and thus raises wages again.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Gegen diese Begründung spricht schon die einfache Thatsache, daß, wie Jedem bekannt, die Löhne nicht von Generation zu Generation schwanken, sondern in viel kürzeren Zwischenräumen. Wir kommen darauf noch zurück.<br> <a id="ab3-kap5-t2" name="ab3-kap5-t2">&nbsp;</a></p>
</div>
<div class="parallel-col-en">
<p>Against this explanation there already speaks the simple fact that, as everyone knows, wages do not fluctuate from generation to generation, but at much shorter intervals. We shall return to this point.<br> <a id="ab3-kap5-t2" name="ab3-kap5-t2"> </a></p>
</div>
</div>
</section>
<section id="the-industrial-reserve-army" class="level5">
<h5 class="anchored" data-anchor-id="the-industrial-reserve-army">2. The industrial reserve army</h5>
<p class="de-subtitle">
</p><ol start="2" type="1">
<li>Die industrielle Reservearmee
<p></p></li>
</ol>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Wir haben bisher angenommen, die Akkumulation gehe vor sich ohne Aenderung in der Zusammensetzung des Kapitals. Solche Aenderungen treten aber im Verlauf der Akkumulation von Zeit zu Zeit mit Nothwendigkeit ein.</p>
</div>
<div class="parallel-col-en">
<p class="fst">We have hitherto assumed that accumulation proceeds without any change in the composition of capital. Such changes, however, necessarily occur from time to time in the course of accumulation.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die <em>technische</em> Zusammensetzung des Kapitals wird von jeder Veränderung in der <em>Produktivkraft der Arbeit</em> berührt. Die Masse der Produktionsmittel, welche ein Arbeiter unter sonst gleichen Umständen in Produkt verwandelt, wächst mit der Produktivität seiner Arbeit. Es wächst die Masse des Rohmaterials, das er verarbeitet, es wachsen die Arbeitsmittel, die er anwendet u.&nbsp;s.&nbsp;w. Mit der Produktivität der Arbeit wächst also die Menge der Produktionsmittel im Verhältniß zu der ihnen einverleibten Arbeitskraft, oder, was dasselbe, die Menge angewandter Arbeit nimmt ab im Verhältniß zu der von ihr bewegten Masse von Produktionsmitteln.</p>
</div>
<div class="parallel-col-en">
<p>The <em>technical</em> composition of capital is affected by every change in the <em>productive power of labour</em>. The mass of means of production which a worker, under otherwise equal circumstances, transforms into product grows with the productivity of his labour. The mass of raw material that he works up grows, the means of labour that he employs grow, and so forth. With the productivity of labour, therefore, the quantity of means of production grows in relation to the labour-power incorporated in them, or, what is the same thing, the quantity of applied labour decreases in relation to the mass of means of production set in motion by it.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Diese Veränderung in der <em>technischen Zusammensetzung</em> des Kapitals spiegelt sich wieder in seiner <em>Werthzusammensetzung.</em> Sie erscheint hier als verhältnißmäßige Abnahme des <em>variablen</em> und Zunahme des <em>konstanten</em> Kapitaltheils. Die Aenderungen in der Werthzusammensetzung des Kapitals entsprechen jedoch nicht genau den Aenderungen seiner technischen Zusammensetzung, da mit dem Wachsthum der Produktivität der Arbeit nicht nur der Umfang der von ihr vernutzten Produktionsmittel <em>steigt,</em> sondern auch deren Werth <em>fällt,</em> jedoch in geringerem Grade, als ihre <em>Masse</em> zunimmt. Im Anfang des vorigen Jahrhunderts war z.&nbsp;B. der in der Spinnerei angelegte Kapitalwerth etwa zur Hälfte konstant, zur Hälfte variabel. Die <em>Masse</em> von Rohmaterial, Arbeitsmitteln u.&nbsp;s.&nbsp;w., die ein Spinner heute bei gleichem Arbeitsaufwand verarbeitet, ist viele hundertmal größer, als damals; das <em>Werthverhältniß</em> zwischen konstantem und variablem Kapital hat sich jedoch viel weniger geändert; es verhält sich das konstante zum variablen Kapital in der Spinnerei jetzt vielleicht wie sieben zu eins.</p>
</div>
<div class="parallel-col-en">
<p>This change in the <em>technical composition</em> of capital is reflected in turn in its <em>value composition</em>. It appears here as a relative decrease of the <em>variable</em> and an increase of the <em>constant</em> portion of capital. The changes in the value composition of capital do not, however, correspond exactly to the changes in its technical composition, since with the growth of the productivity of labour not only does the extent of the means of production consumed by it <em>rise</em>, but their value also <em>falls</em>, yet to a lesser degree than their <em>mass</em> increases. At the beginning of the last century, for example, the capital value invested in spinning was about half constant and half variable. The <em>mass</em> of raw material, means of labour, and so on, that a spinner today works up with the same expenditure of labour is many hundreds of times greater than it was then; the <em>value ratio</em> between constant and variable capital has, however, changed much less; the constant capital in spinning is now perhaps related to the variable as seven to one.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Auf jeden Fall aber bedeutet das Wachsthum der Produktivität der Arbeit unter der kapitalistischen Produktionsweise <em>verhältnißmäßige</em> Abnahme des variablen Kapitals.</p>
</div>
<div class="parallel-col-en">
<p>In any case, however, the growth of the productivity of labour under the capitalist mode of production means a <em>relative</em> decrease of variable capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die Produktivität der Arbeit und die Akkumulation des Kapitals stehen aber in engster Wechselbeziehung zu einander.</p>
</div>
<div class="parallel-col-en">
<p>The productivity of labour and the accumulation of capital stand, however, in the closest reciprocal relation to one another.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die Waarenproduktion bedingt es, daß die Produktionsmittel Privateigenthum Einzelner sind. Die Entwicklung der gesellschaftlichen Produktivkraft der Arbeit setzt aber Kooperation auf großer Stufenleiter voraus, große Arbeitsräume, große Massen von Rohstoffen und Arbeitsmitteln u.&nbsp;s.&nbsp;w. Der Besitz so riesenhafter Produktionsmittel in den Händen Einzelner ist unter der Herrschaft der Waarenproduktion nur möglich, wenn individuelle Kapitalien in genügendem Umfange akkumulirt worden sind. „Der Boden der Waarenproduktion kann die Produktion auf großer Stufenleiter nur in kapitalistischer Form tragen.“ Eine gewisse Höhe der Akkumulation von Kapital ist also Vorbedingung einer gewissen Höhe der Produktivkraft der Arbeit. Jede Methode der Steigerung der Produktivkraft der Arbeit wird aber unter der kapitalistischen Produktionsweise zu einer Methode der gesteigerten Produktion von Mehrwerth und ermöglicht damit eine Steigerung der Akkumulation. Diese selbst bewirkt ihrerseits wieder eine Erweiterung der Stufenleiter der Produktion, welche wiederum der mächtigste Stachel zu neuer Steigerung der Produktivkraft der Arbeit ist. Die Akkumulation des Kapitals und die Produktivkraft der Arbeit entwickeln einander also wechselseitig immer mehr und mehr.</p>
</div>
<div class="parallel-col-en">
<p>Commodity production entails that the means of production are the private property of individuals. The development of the social productive power of labour, however, presupposes cooperation on a large scale, large workspaces, great masses of raw materials and means of labour, and so forth. The possession of such gigantic means of production in the hands of individuals is possible, under the rule of commodity production, only if individual capitals have been accumulated to a sufficient extent. “The soil of commodity production can bear production on a large scale only in capitalist form.” A certain height of the accumulation of capital is therefore the precondition of a certain height of the productive power of labour. Every method of raising the productive power of labour becomes, however, under the capitalist mode of production, a method of the heightened production of surplus value, and thereby makes possible a heightening of accumulation. This in turn brings about an extension of the scale of production, which again is the most powerful spur to a new heightening of the productive power of labour. The accumulation of capital and the productive power of labour thus develop each other reciprocally more and more.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Dem Einfluß des Wachsthums der einzelnen Kapitale durch die Akkumulation wirkt entgegen die gleichzeitige Spaltung alter Kapitalien, z.&nbsp;B. durch Erbtheilungen, und die Ablösung neuer selbständiger Kapitalien. Diese Gegenwirkung gegen die Akkumulation wird aber mehr als aufgehoben durch die <em>Zentralisation,</em> die <em>Vereinigung bereits gebildeter Kapitalien,</em> wie sie namentlich durch die Aufsaugung der kleinen Kapitalien durch die großen hervorgerufen wird. Diese Zentralisation bewirkt ebenso eine Steigerung der Produktivität, eine Aenderung der technischen Zusammensetzung des Kapitals, wie die Akkumulation. Anderseits fördert die Akkumulation die Zentralisation und umgekehrt. Ein je größeres Kapital ich akkumulirt habe, desto leichter wird es im Konkurrenzkampf die kleinen besiegen und aufsaugen. Je mehr kleine Kapitalien mein Kapital aufgesaugt hat, desto größer die Produktivität der von ihm in Gang gehaltenen Arbeit, desto umfangreicher die Akkumulation.</p>
</div>
<div class="parallel-col-en">
<p>The influence of the growth of the individual capitals through accumulation is counteracted by the simultaneous splitting up of old capitals, for example through divisions of inheritance, and by the detachment of new independent capitals. This counteraction against accumulation is, however, more than cancelled by <em>centralisation</em>, the <em>union of capitals already formed</em>, such as is brought about above all by the absorption of the small capitals by the large. This centralisation, like accumulation, likewise brings about a heightening of productivity, a change in the technical composition of capital. On the other hand, accumulation promotes centralisation and vice versa. The larger the capital I have accumulated, the more easily will it, in the competitive struggle, defeat and absorb the small ones. The more small capitals my capital has absorbed, the greater the productivity of the labour it keeps in motion, the more extensive the accumulation.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die Ansammlung riesiger Kapitalmassen in wenigen Händen entwickelt aber nicht blos die Produktivität in den bereits der kapitalistischen Produktionsweise unterworfenen Arbeitszweigen. Eine Reihe kleiner aus den großen Industriezweigen vertriebenen Kapitalien wird in Arbeitszweige gedrängt, in denen der kapitalistische Betrieb noch nicht festen Fuß gefaßt hat, wo ein kleines Kapital noch konkurrenzfähig ist, und bereitet so den Boden vor für die Einverleibung auch dieser Gewerbszweige in den Bereich des Kapitalismus.</p>
</div>
<div class="parallel-col-en">
<p>The amassing of gigantic masses of capital in few hands develops, however, not only productivity in those branches of labour already subjected to the capitalist mode of production. A number of small capitals driven out of the great branches of industry are forced into branches of labour in which capitalist enterprise has not yet gained a firm foothold, where a small capital is still able to compete, and thus prepares the ground for the incorporation of these branches of trade too into the domain of capitalism.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>So sehen wir die kapitalistische Produktionsweise in einer beständigen technischen Revolution begriffen, deren Folge stetig fortschreitende Vergrößerung des konstanten Kapitals, verhältnißmäßige Verkleinerung des variablen Kapitals.</p>
</div>
<div class="parallel-col-en">
<p>Thus we see the capitalist mode of production caught up in a constant technical revolution, the consequence of which is a steadily advancing enlargement of the constant capital and a relative diminution of the variable capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Und die verhältnißmäßige Abnahme des variablen Kapitals schreitet ungleich schneller, als die Akkumulation. Das im Fortgang der Akkumulation neugebildete Kapital beschäftigt im Verhältniß zu seiner Größe immer weniger zuschüssige Arbeiter. Gleichzeitig mit der Akkumulation geht aber auch die Revolutionirung des <em>alten</em> Kapitals vor sich. Wenn eine Maschine abgenutzt ist, so wird sie, wenn inzwischen ein technischer Fortschritt stattgefunden, nicht durch eine andere, die ihr gleich, sondern durch eine verbesserte ersetzt, durch deren Anwendung ein Arbeiter mehr Produkt als vorher liefern kann. Das alte Kapital wird in immer produktiverer Form neu produzirt; das hat aber zur Folge, daß es immer mehr Arbeiter entläßt, die es beschäftigte.</p>
</div>
<div class="parallel-col-en">
<p>And the relative decrease of variable capital advances incomparably faster than accumulation. The capital newly formed in the course of accumulation employs, in proportion to its magnitude, ever fewer additional workers. Simultaneously with accumulation, however, the revolutionising of the <em>old</em> capital also takes place. When a machine is worn out, then, if a technical advance has meanwhile taken place, it is replaced not by another of the same kind, but by an improved one, through whose employment a worker can deliver more product than before. The old capital is reproduced in an ever more productive form; this, however, has the consequence that it dismisses ever more of the workers it employed.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die Zentralisation ist einer der mächtigsten Hebel dieser Umwandlung des alten Kapitals.</p>
</div>
<div class="parallel-col-en">
<p>Centralisation is one of the most powerful levers of this transformation of the old capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Je rascher die Zentralisation und technische Revolution des alten Kapitals vor sich geht, desto beschleunigter muß die Akkumulation neuen Kapitals vor sich gehen, wenn die Zahl der beschäftigten Arbeiter nicht abnehmen soll. Je schneller aber die Akkumulation vor sich geht, desto mehr wird die Zentralisation und technische Revolution gefördert.</p>
</div>
<div class="parallel-col-en">
<p>The more rapidly the centralisation and technical revolution of the old capital proceeds, the more accelerated must the accumulation of new capital proceed, if the number of employed workers is not to decrease. But the faster accumulation proceeds, the more centralisation and technical revolution are promoted.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Die Malthusianer erzählen uns, die „Uebervölkerung“ rühre davon her, daß die Lebensmittel (oder genauer gesprochen, das variable Kapital) in einer <em>arithmetischen Progression</em> wachsen, im Verhältniß von 1&nbsp;:&nbsp;2&nbsp;:&nbsp;3&nbsp;:&nbsp;4&nbsp;:&nbsp;5 u.&nbsp;s.&nbsp;w., indessen die Bevölkerung das Streben habe, in <em>geometrischer Progression</em> zuzunehmen, wie 1&nbsp;:&nbsp;2&nbsp;:&nbsp;4&nbsp;:&nbsp;8&nbsp;:&nbsp;16 u.&nbsp;s.&nbsp;w. Die Zunahme der Bevölkerung eile daher der der Lebensmittel stets voraus: die natürliche Folge davon sei Laster und Elend.</p>
</div>
<div class="parallel-col-en">
<p>The Malthusians tell us that “overpopulation” arises from the fact that the means of subsistence (or, more precisely speaking, the variable capital) grow in an <em>arithmetical progression</em>, in the ratio of 1 : 2 : 3 : 4 : 5 and so on, while the population has the tendency to increase in a <em>geometrical progression</em>, as 1 : 2 : 4 : 8 : 16 and so on. The increase of the population therefore always hastens ahead of that of the means of subsistence: the natural consequence of this is vice and misery.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Was aber in Wirklichkeit progressiv fortschreitet, das ist die <em>Abnahme</em> des variablen Kapitals, gleichzeitig mit dem <em>Wachsthum</em> des Gesammtkapitals. Das variable Kapital, wenn ursprünglich ½ des Gesammtkapitals, wird fortschreitend nur <sup><small>1</small></sup>/<small><small>3</small></small>, <sup><small>1</small></sup>/<small><small>4</small></small>, <sup><small>1</small></sup>/<small><small>5</small></small>, <sup><small>1</small></sup>/<small><small>6</small></small> u.&nbsp;s.&nbsp;w. des Gesammtkapitals.</p>
</div>
<div class="parallel-col-en">
<p>What in reality advances progressively, however, is the <em>decrease</em> of variable capital, simultaneously with the <em>growth</em> of the total capital. The variable capital, if originally ½ of the total capital, becomes progressively only <sup><small>1</small></sup>/<small><small>3</small></small>, <sup><small>1</small></sup>/<small><small>4</small></small>, <sup><small>1</small></sup>/<small><small>5</small></small>, <sup><small>1</small></sup>/<small><small>6</small></small> and so on of the total capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="quoteb">„Diese mit dem Wachsthum des Gesammtkapitals beschleunigte und rascher als sein eigenes Wachsthum beschleunigte relative Abnahme seines variablen Bestandtheiles scheint umgekehrt stets rascheres absolutes Wachsthum der Arbeiterbevölkerung als das des variablen Kapitals oder ihrer Beschäftigungsmittel. Die kapitalistische Akkumulation produzirt vielmehr und zwar im Verhältniß zu ihrer Euergie und ihrem Umfang, beständig eine relative, das heißt, <em>für die Verwerthungsbedürfnisse des Kapitals überschüssige,</em> daher überflüssige oder Zuschuß-Arbeiterbevölkerung.“</p>
</div>
<div class="parallel-col-en">
<p class="quoteb">„This relative decrease of its variable constituent, accelerated with the growth of the total capital and accelerated more rapidly than its own growth, appears, conversely, as an always more rapid absolute growth of the working population than that of the variable capital or of its means of employment. Rather, capitalist accumulation constantly produces — and indeed in proportion to its energy and its extent — a relative, that is, an <em>excess working population surplus to the valorisation requirements of capital,</em> hence a superfluous or supplementary working population.“</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Der Wechsel in der Zusammensetzung des gesellschaftlichen Gesammtkapitals geht nicht in allen seinen Theilen gleichmäßig vor sich. Hier wächst das Kapital durch die Akkumulation, ohne daß diese zunächst die gegebene technische Grundlage ändert, und nimmt daher zuschüssige Arbeitskräfte im Verhältniß seines Wachsthums auf. Dort verändert sich die Zusammensetzung des Kapitals ohne Wachsthum seiner absoluten Größe, blos durch Neuersatz alten Kapitals in produktiverer Form; – und die Zahl der beschäftigten Arbeiter sinkt relativ und absolut. Zwischen diesen beiden extremen Fällen treten unzählige Kombinationen ein, bedingt durch das Aufeinanderwirken von Akkumulation, Zentralisation und Umwandlung alten Kapitals in produktivere Form, die alle entweder direkte Entlassung von Arbeitern zur Folge haben, „oder die mehr unscheinbare, aber nicht minder wirksame erschwerte Aufsaugung der zuschüssigen Arbeiterbevölkerung in ihre gewohnten Abzugskanäle.“ Die Arbeiterbevölkerung wird so in beständigem Fluß erhalten, hier angezogen, dort abgestoßen, und diese Bewegung wird um so heftiger, je rascher der Wechsel in der Zusammensetzung des Kapitals, je größerr die Produktivität der Arbeit, je mächtiger die Akkumulation von Kapital.</p>
</div>
<div class="parallel-col-en">
<p class="fst">The change in the composition of the aggregate social capital does not proceed uniformly in all its parts. In one place capital grows through accumulation without this accumulation at first altering the given technical basis, and therefore takes up additional labour-power in proportion to its growth. In another place the composition of the capital changes without any growth of its absolute magnitude, merely through the replacement of old capital in a more productive form; — and the number of the workers employed falls both relatively and absolutely. Between these two extreme cases countless combinations occur, conditioned by the interaction of accumulation, centralisation, and the transformation of old capital into a more productive form, all of which have as their consequence either the direct dismissal of workers, „or the more inconspicuous but no less effective more difficult absorption of the additional working population into their accustomed channels of outflow.“ The working population is thus kept in constant flux, here attracted, there repelled, and this movement becomes the more violent, the more rapid the change in the composition of the capital, the greater the productivity of labour, the more powerful the accumulation of capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Marx bringt mehrere Belege aus dem englischen Zensus für die verhältnißmäßige und oft auch absolute Abnahme der Zahl der beschäftigten Arbeiter in zahlreichen Industriezweigen. Aus neueren Zählungen entnehmen wir folgende zwei Beispiele einer absoluten Abnahme der Zahl der beschäftigten Arbeiter bei gleichzeitiger Ausdehnung der Produktion.</p>
</div>
<div class="parallel-col-en">
<p>Marx adduces several pieces of evidence from the English census for the relative, and often also absolute, decrease in the number of workers employed in numerous branches of industry. From more recent censuses we take the following two examples of an absolute decrease in the number of workers employed with a simultaneous expansion of production.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Das eine Beispiel zeigt uns die <em>Baumwollindustrie Großbritanniens</em> in der Periode von 1861 bis 1871. Es betrug in derselben</p>
</div>
<div class="parallel-col-en">
<p>The one example shows us the <em>cotton industry of Great Britain</em> in the period from 1861 to 1871. In it there were</p>
</div>
</div>
<div class="table-block">
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th"><p>Die Zahl der</p></th>
<td rowspan="5"><p>&nbsp;&nbsp;&nbsp;&nbsp;</p></td>
<th data-quarto-table-cell-role="th"><p>1861</p></th>
<th data-quarto-table-cell-role="th"><p>1871</p></th>
</tr>
<tr class="even">
<td><p>Fabriken</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.887</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.483</p></td>
</tr>
<tr class="odd">
<td><p>Spindeln</p></td>
<td><p>30.387.467</p></td>
<td><p>34.695.221</p></td>
</tr>
<tr class="even">
<td><p>Dampfwebstühle</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;399.992</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;440.676</p></td>
</tr>
<tr class="odd">
<td><p>Arbeiter</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;456.646</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;450.087</p></td>
</tr>
</tbody>
</table>

</div>
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th"><p>The number of</p></th>
<td rowspan="5"></td>
<th data-quarto-table-cell-role="th"><p>1861</p></th>
<th data-quarto-table-cell-role="th"><p>1871</p></th>
</tr>
<tr class="even">
<td><p>Factories</p></td>
<td><p>2.887</p></td>
<td><p>2.483</p></td>
</tr>
<tr class="odd">
<td><p>Spindles</p></td>
<td><p>30.387.467</p></td>
<td><p>34.695.221</p></td>
</tr>
<tr class="even">
<td><p>Steam looms</p></td>
<td><p>399.992</p></td>
<td><p>440.676</p></td>
</tr>
<tr class="odd">
<td><p>Workers</p></td>
<td><p>456.646</p></td>
<td><p>450.087</p></td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Wir sehen gleichzeitig mit der Abnahme der Zahl der beschäftigten Arbeiter eine Abnahme der Zahl der Fabriken und eine Zunahme der Spindeln und Maschinenstühle; Anzeichen einer Zentralisation und Akkumulation von Kapital.</p>
</div>
<div class="parallel-col-en">
<p class="fst">We see, simultaneously with the decrease in the number of workers employed, a decrease in the number of factories and an increase in the number of spindles and machine looms; indications of a centralisation and accumulation of capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Von 1895 bis 1904 stieg der Baumwollkonsum in England von 1.550 Millionen Pfund auf 1.700 Millionen, gleichzeitig sank die Zahl der Arbeiter in den Baumwollfabriken von 539.000 auf 523.000.</p>
</div>
<div class="parallel-col-en">
<p>From 1895 to 1904 cotton consumption in England rose from 1,550 million pounds to 1,700 million, while at the same time the number of workers in the cotton factories fell from 539,000 to 523,000.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Ein ähnliches Bild bieten manche Zweige der deutschen Textilindustrie: starke Abnahme der Zahl der Arbeiter, die aber nur auf die Kleinbetriebe beschränkt ist. Die Großbetriebe und ihre Arbeiter nehmen zu – also starke Zentralisation und Akkumulation von Kapital bei gleichzeitiger Freisetzung von Arbeitern. So finden wir z.&nbsp;B. in der <em>Seidenweberei</em> des Deutschen Reiches:</p>
</div>
<div class="parallel-col-en">
<p>A similar picture is offered by several branches of the German textile industry: a strong decrease in the number of workers, which, however, is confined solely to the small-scale enterprises. The large-scale enterprises and their workers increase — thus a strong centralisation and accumulation of capital together with a simultaneous setting-free of workers. Thus we find, for example, in the <em>silk-weaving</em> industry of the German Reich:</p>
</div>
</div>
<div class="table-block">
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd" data-valign="top">
<th data-quarto-table-cell-role="th"><p>Jahr</p></th>
<td rowspan="6"><p>&nbsp;&nbsp;&nbsp;</p></td>
<td colspan="2"><p><strong>Kleinbetriebe</strong><br>
(bis 5 Arbeiter)</p></td>
<td rowspan="6"><p>&nbsp;&nbsp;&nbsp;</p></td>
<td colspan="2"><p><strong>Mittelbetriebe</strong><br>
(6 bis 50 Arbeiter)</p></td>
<td rowspan="6"><p>&nbsp;&nbsp;&nbsp;</p></td>
<td colspan="2"><p><strong>Großbetriebe</strong><br>
(über 50 Arbeiter)</p></td>
</tr>
<tr class="even">
<td><p><br>
</p></td>
<td><p>Betriebe</p></td>
<td><p>Arbeiter</p></td>
<td><p>Betriebe</p></td>
<td><p>Arbeiter</p></td>
<td><p>Betriebe</p></td>
<td><p>Arbeiter</p></td>
</tr>
<tr class="odd">
<td><p>1882</p></td>
<td><p>&nbsp;&nbsp;39.500</p></td>
<td><p>&nbsp;&nbsp;57.782</p></td>
<td><p>412</p></td>
<td><p>4.902</p></td>
<td><p>&nbsp;&nbsp;69</p></td>
<td><p>&nbsp;&nbsp;13.580</p></td>
</tr>
<tr class="even">
<td><p>1895</p></td>
<td><p>&nbsp;&nbsp;16.527</p></td>
<td><p>&nbsp;&nbsp;20.484</p></td>
<td><p>192</p></td>
<td><p>3.169</p></td>
<td><p>140</p></td>
<td><p>&nbsp;&nbsp;32.121</p></td>
</tr>
<tr class="odd">
<td><p>1897</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;8.272</p></td>
<td><p>&nbsp;&nbsp;12.823</p></td>
<td><p>346</p></td>
<td><p>5.650</p></td>
<td><p>240</p></td>
<td><p>&nbsp;&nbsp;48.719</p></td>
</tr>
<tr class="even">
<td><p>Zuname (+)<br>
oder Abnahme (−)</p></td>
<td><p>−31.228</p></td>
<td><p>−44.959</p></td>
<td><p>−66</p></td>
<td><p>&nbsp;&nbsp;&nbsp;748</p></td>
<td><p>+171</p></td>
<td><p>+35.139</p></td>
</tr>
</tbody>
</table>

</div>
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd" data-valign="top">
<th data-quarto-table-cell-role="th"><p>Year</p></th>
<td rowspan="6"></td>
<td colspan="2"><p><strong>Small-scale enterprises</strong><br>
(up to 5 workers)</p></td>
<td rowspan="6"></td>
<td colspan="2"><p><strong>Medium-scale enterprises</strong><br>
(6 to 50 workers)</p></td>
<td rowspan="6"></td>
<td colspan="2"><p><strong>Large-scale enterprises</strong><br>
(over 50 workers)</p></td>
</tr>
<tr class="even">
<td><p><br>
</p></td>
<td><p>Enterprises</p></td>
<td><p>Workers</p></td>
<td><p>Enterprises</p></td>
<td><p>Workers</p></td>
<td><p>Enterprises</p></td>
<td><p>Workers</p></td>
</tr>
<tr class="odd">
<td><p>1882</p></td>
<td><p>39.500</p></td>
<td><p>57.782</p></td>
<td><p>412</p></td>
<td><p>4.902</p></td>
<td><p>69</p></td>
<td><p>13.580</p></td>
</tr>
<tr class="even">
<td><p>1895</p></td>
<td><p>16.527</p></td>
<td><p>20.484</p></td>
<td><p>192</p></td>
<td><p>3.169</p></td>
<td><p>140</p></td>
<td><p>32.121</p></td>
</tr>
<tr class="odd">
<td><p>1897</p></td>
<td><p>8.272</p></td>
<td><p>12.823</p></td>
<td><p>346</p></td>
<td><p>5.650</p></td>
<td><p>240</p></td>
<td><p>48.719</p></td>
</tr>
<tr class="even">
<td><p>Increase (+)<br>
or decrease (−)</p></td>
<td><p>−31.228</p></td>
<td><p>−44.959</p></td>
<td><p>−66</p></td>
<td><p>748</p></td>
<td><p>+171</p></td>
<td><p>+35.139</p></td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Ebenso in der Leinenweberei:</p>
</div>
<div class="parallel-col-en">
<p class="fst">Likewise in the linen-weaving industry:</p>
</div>
</div>
<div class="table-block">
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd">
<td><p>1882</p></td>
<td rowspan="4"><p>&nbsp;&nbsp;&nbsp;&nbsp;</p></td>
<td><p>&nbsp;&nbsp;71.915</p></td>
<td><p>&nbsp;&nbsp;91.039</p></td>
<td rowspan="4"><p>&nbsp;&nbsp;&nbsp;&nbsp;</p></td>
<td><p>&nbsp;&nbsp;404</p></td>
<td><p>5.226</p></td>
<td rowspan="4"><p>&nbsp;&nbsp;&nbsp;&nbsp;</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;73</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;7.543</p></td>
</tr>
<tr class="even">
<td><p>1895</p></td>
<td><p>&nbsp;&nbsp;34.082</p></td>
<td><p>&nbsp;&nbsp;43.228</p></td>
<td><p>&nbsp;&nbsp;291</p></td>
<td><p>4.598</p></td>
<td><p>&nbsp;&nbsp;120</p></td>
<td><p>&nbsp;&nbsp;19.966</p></td>
</tr>
<tr class="odd">
<td><p>1907</p></td>
<td><p>&nbsp;&nbsp;14.275</p></td>
<td><p>&nbsp;&nbsp;18.949</p></td>
<td><p>&nbsp;&nbsp;265</p></td>
<td><p>5.214</p></td>
<td><p>&nbsp;&nbsp;180</p></td>
<td><p>&nbsp;&nbsp;28.177</p></td>
</tr>
<tr class="even">
<td><p>Zunahme (+)<br>
oder Abnahme (−)</p></td>
<td><p>−57.640</p></td>
<td><p>−72.090</p></td>
<td><p>−139</p></td>
<td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;−12</p></td>
<td><p>+107</p></td>
<td><p>+20.634</p></td>
</tr>
</tbody>
</table>

</div>
<div class="table-scroll">

<table class="caption-top table" data-align="center" data-cellpadding="3" data-cellspacing="3">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<tbody>
<tr class="odd">
<td><p>1882</p></td>
<td rowspan="4"></td>
<td><p>71.915</p></td>
<td><p>91.039</p></td>
<td rowspan="4"></td>
<td><p>404</p></td>
<td><p>5.226</p></td>
<td rowspan="4"></td>
<td><p>73</p></td>
<td><p>7.543</p></td>
</tr>
<tr class="even">
<td><p>1895</p></td>
<td><p>34.082</p></td>
<td><p>43.228</p></td>
<td><p>291</p></td>
<td><p>4.598</p></td>
<td><p>120</p></td>
<td><p>19.966</p></td>
</tr>
<tr class="odd">
<td><p>1907</p></td>
<td><p>14.275</p></td>
<td><p>18.949</p></td>
<td><p>265</p></td>
<td><p>5.214</p></td>
<td><p>180</p></td>
<td><p>28.177</p></td>
</tr>
<tr class="even">
<td><p>Increase (+)<br>
or decrease (−)</p></td>
<td><p>−57.640</p></td>
<td><p>−72.090</p></td>
<td><p>−139</p></td>
<td><p>−12</p></td>
<td><p>+107</p></td>
<td><p>+20.634</p></td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="fst">Die Zahl der Arbeiter in der Seidenweberei und Leinenweberei zusammen hat in den 25 Jahren um 60.540 <em>abgenommen,</em> aber die Abnahme war nur durch den Rückgang des Kleinbetriebs verschuldet, dessen Betriebe in beiden Produktionszweigen um 88.868, um 80 Prozent abnahmen, während die Zahl ihrer Arbeiter um 11.6959 sank. Dagegen vermehrten sich die Großbetriebe von 142 auf 420, ihre Zahl <em>verdreifachte</em> sich fast, und ihre Arbeiterzahl wuchs von 21.123 auf 76.896, also <em>um mehr als das Dreifache.</em></p>
</div>
<div class="parallel-col-en">
<p class="fst">The number of workers in silk-weaving and linen-weaving together <em>decreased</em> by 60,540 in the 25 years, but the decrease was caused solely by the decline of the small-scale enterprise, whose establishments in both branches of production decreased by 88,868, by 80 per cent, while the number of their workers fell by 116,959. On the other hand, the large-scale enterprises increased from 142 to 420, their number almost <em>tripled,</em> and the number of their workers grew from 21,123 to 76,896, thus <em>by more than threefold.</em></p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wir haben bisher angenommen, daß der Zu- oder Abnahme des variablen Kapitals genau die Zu- oder Abnahme der beschäftigten Arbeiterzahl entspricht. Dies ist jedoch nicht immer der Fall. Wenn der Fabrikant bei gleichbleibendem Arbeitspreis <em>die Arbeitszeit verlängert,</em> so wird er mehr Arbeitslohn ausgeben; das variable Kapital wird wachsen, ohne daß mehr Arbeiter beschäftigt werden müssen – deren Zahl kann gleichzeitig sogar sinken.</p>
</div>
<div class="parallel-col-en">
<p>We have hitherto assumed that the increase or decrease of the variable capital corresponds exactly to the increase or decrease of the number of workers employed. This, however, is not always the case. If the manufacturer, the price of labour remaining the same, <em>lengthens the working time,</em> he will spend more in wages; the variable capital will grow, without more workers having to be employed – their number may even fall at the same time.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Nehmen wir an, ein Unternehmer beschäftige 1000 Arbeiter, der Arbeitstag betrage 10 Stunden, der Tageslohn 2 Mark. Er will zuschüssiges Kapital in seinem Betrieb anlegen. Er kann dies in der Weise thun, daß er die Betriebräumlichkeiten erweitert, neue Maschinen anschafft und mehr Arbeiter einstellt, Er kan1i aber auch das zuschüssige Kapital, soweit es uicht zur Anschaffung von mehr Rohmaterial dieneu muß, in der Weise anwenden, daß er die Arbeitszeit der bereits beschäftigten Arbeiter verlängert. Nehmen wir an, er verlängere sie um 5 Stunden; der Preis der Arbeit bleibe derselbe; der Tageslohn wird dann 8 Mark betragen, da 3 variable Kapital wird – unter sonst gleichen Umständen – um 50 Prozent gestiegen sein, ohne daß die Zahl der Arbeiter gewachsen wäre. Jeder Kapitalist hat aber das Interesse, eine Vermehrung der Arbeit eher durch Verlängerung der Arbeitszeit oder Vergrößerung der Intensität der Arbeit als durch Vermehrung der Arbeiterzahl zu erzielen, da der Betrag des konstanten Kapitals, den er auszulegen hat, in ersterem Fall viel langsamer wächst, als in letzterem. Und dies Interesse ist um so stärker, je größer die Stufenleiter der Produktion. Seine Kraft wächst also mit der Akkumulation des Kapitals.</p>
</div>
<div class="parallel-col-en">
<p>Let us assume that an entrepreneur employs 1000 workers, that the working day amounts to 10 hours, and the daily wage to 2 marks. He wishes to invest additional capital in his enterprise. He can do this in such a way that he enlarges the business premises, procures new machines and takes on more workers. But he can also employ the additional capital, in so far as it need not serve for the procurement of more raw material, in such a way that he lengthens the working time of the workers already employed. Let us assume that he lengthens it by 5 hours; that the price of labour remains the same; the daily wage will then amount to 3 marks, so that the variable capital will – other circumstances being equal – have risen by 50 per cent, without the number of workers having grown. But every capitalist has an interest in achieving an increase of labour rather through the lengthening of the working time or the enlargement of the intensity of labour than through an increase of the number of workers, since the amount of constant capital which he has to lay out grows much more slowly in the former case than in the latter. And this interest is all the stronger the greater the scale of production. Its force therefore grows with the accumulation of capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wenn z.&nbsp;B. das Arbeitsmittel des Arbeiters ein Spaten ist, der 2 Mark kostet, wird der Unternehmer sich kaum sehr dagegen sträuben, eine Vermehrung der Arbeit durch entsprechende Vermehrung der Zahl der Arbeiter zu erzielen. Anders wenn der Arbeiter eine Maschinerie anwendet, die 100.000 Mark kostet.</p>
</div>
<div class="parallel-col-en">
<p>If, for example, the worker's means of labour is a spade costing 2 marks, the entrepreneur will scarcely resist very much achieving an increase of labour through a corresponding increase in the number of workers. It is otherwise when the worker applies a machinery costing 100,000 marks.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Mit der Akkumulation des Kapitals wächst aber nicht nur das Bestreben der Kapitalisten, eine Vermehrung der Arbeit ohne entsprechende Vermehrung der Zahl der Arbeiter zu erzielen, es nimmt damit auch die Kraft der Arbeiterklasse ab, dieser Tendenz Widerstand zu leisten. Die durch die Akkumulation des Kapitals produzirte überschüssige Arbeitermenge verringert durch ihre Konkurrenz die Widerstandskraft der beschäftigten Arbeiter. Diese werden so gezwungen, sich zur Ueberarbeit zu verstehen; die Ueberarbeit wieder schwellt die Reihen der überflüssigen Arbeiterbevölkerung. Die Arbeitslosigkeit der Einen bedingt die Ueberarbeit der Anderen und umgekehrt.</p>
</div>
<div class="parallel-col-en">
<p>But with the accumulation of capital there grows not only the striving of the capitalists to achieve an increase of labour without a corresponding increase in the number of workers; with it there also diminishes the power of the working class to offer resistance to this tendency. The surplus quantity of workers produced by the accumulation of capital reduces, through its competition, the power of resistance of the employed workers. These are thus compelled to submit to overwork; and the overwork in turn swells the ranks of the superfluous working population. The unemployment of the one conditions the overwork of the other, and vice versa.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wir sehen, die Akkumulation des Kapitals mit ihren Begleiterscheinungen und Folgen, der Zentralisation der Kapitalien, der technischen Umwälzung des alten Kapitals, der Ueberarbeit u.&nbsp;s.&nbsp;w., hat das Bestreben, die Zahl der <em>beschäftigten</em> Arbeiter im Verhältniß zum angewendeten Gesammtkapital, mitunter auch absolut, zu <em>verringern.</em></p>
</div>
<div class="parallel-col-en">
<p>We see that the accumulation of capital, with its accompanying phenomena and consequences – the centralisation of capitals, the technical revolutionising of the old capital, overwork, etc. – has the striving to <em>reduce</em> the number of <em>employed</em> workers in proportion to the total capital applied, and sometimes even absolutely.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Sie <em>vermehrt</em> aber gleichzeitig die Zahl der sich <em>anbietenden,</em> der dem Kapital zur Verfügung stehenden Arbeiter in einem Maße, das weit über das der Vermehrung der Bevölkerung überhaupt hinausgeht.</p>
</div>
<div class="parallel-col-en">
<p>But at the same time it <em>increases</em> the number of the workers who <em>offer themselves,</em> who stand at the disposal of capital, to a degree that far exceeds that of the increase of the population in general.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wir haben im zweiten Abschnitt gesehen, wie die Manufaktur und noch mehr die große Industrie im Fortgang ihrer Entwicklung ungelernte Arbeitskräfte an Stelle von gelernten verwendbar machen; die Lehrzeit des Arbeiters schrumpft auf ein Minimum zusammen, der Arbeiter wird früher in Stand gesetzt, vom Kapital angewendet zu werden, die Zeit seiner Reproduktion verkürzt sich. Gleichzeitig werden erwachsene männliche Arbeiter in vielen Arbeitszweigen durch Frauen und Kinder entbehrlich gemacht. Damit wird nicht nur unmittelbar die Arbeiterarmee ungeheuer vermehrt; die ökonomische Selbständigkeit von Mädchen und jungen Leuten, ihr Zusammenarbeiten, sowie die Möglichkeit, die Kinder in früher Jugend mitverdienen lassen zu können, befördern frühe Eheschließungen, und verkürzen so ebenfalls die Reproduktionszeit der Arbeiterklasse.</p>
</div>
<div class="parallel-col-en">
<p>We have seen in the second section how manufacture, and still more large-scale industry, in the course of their development make unskilled labour-power usable in place of skilled; the worker's period of apprenticeship shrinks to a minimum, the worker is put in a position to be applied by capital earlier, the time of his reproduction is shortened. At the same time adult male workers are rendered dispensable in many branches of labour by women and children. Thereby not only is the workers' army immediately enlarged to an enormous degree; the economic independence of girls and young people, their working together, as well as the possibility of being able to let the children earn along with them in early youth, promote early marriages, and thus likewise shorten the reproduction time of the working class.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Eine weitere mächtige Ursache des raschen Anschwellens der Arbeiterarmee tritt in Wirksamkeit, sobald die kapitalistische Produktionsweise sich der <em>Landwirthschaft</em> bemächtigt. Hier bewirkt die Zunahme der Produktivität von vornherein nicht blos eine verhältnißmäßige, sondern auch eine absolute Abnahme der Zahl der beschäftigten Arbeiter. In Großbritannien betrug die Anzahl der in der Landwirthschaft Beschäftigten 1861 2.210.449, 1871 nur noch 1.514.601, eine Abnahme von fast 700.000. Die so „überzählig“ gemachten ziehen in die industriellen Bezirke, soweit sie nicht ganz auswandern, und vermehren dort die Arbeiterarmee, die sich dem Kapital anbietet.</p>
</div>
<div class="parallel-col-en">
<p>A further powerful cause of the rapid swelling of the workers' army comes into effect as soon as the capitalist mode of production takes possession of <em>agriculture.</em> Here the increase of productivity brings about from the outset not merely a proportional but also an absolute decrease in the number of employed workers. In Great Britain the number of those employed in agriculture amounted in 1861 to 2,210,449, in 1871 to only 1,514,601, a decrease of almost 700,000. Those thus rendered "superfluous" move into the industrial districts, in so far as they do not emigrate altogether, and increase there the workers' army that offers itself to capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Vergessen wir endlich nicht die Wirkung der Eisenbahnen und Dampfschiffe, die es dem Kapital ermöglichen, neue Arbeitermassen aus industriell zurückgebliebenen Gegenden zu ziehen, Irländer, Polen, Slovaken, Italiener, Chinesen u.&nbsp;s.&nbsp;w.</p>
</div>
<div class="parallel-col-en">
<p>Let us finally not forget the effect of the railways and steamships, which enable capital to draw new masses of workers from industrially backward regions – Irishmen, Poles, Slovaks, Italians, Chinese, and so forth.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>So vermehrt sich die Arbeiterbevölkerung ungemein rasch, rascher, als das Bedürfniß des Kapitals nach anzuwendenden Arbeitskräften, und die Folge ist eine relative <em>Uebervölkerung,</em> die, wie wir gesehen, durch die Akkumulation des Kapitals erzeugt wird; nicht durch die Zunahme der <em>Unproduktivität</em> der Arbeit, und die Folge ist eine relative <em>Uebervölkerung,</em> die, wie wir gesehen, durch die Akkumulation des Kapitals erzeugt wird; nicht durch die Zunahme der <em>Unproduktivität</em> der Arbeit, wie die Oekonomen behaupten, sondern durch das Wachsthum ihrer <em>Produktivität.</em></p>
</div>
<div class="parallel-col-en">
<p>Thus the working population increases exceedingly rapidly, more rapidly than the need of capital for labour-power to be applied, and the consequence is a relative <em>overpopulation</em> which, as we have seen, is produced by the accumulation of capital; not by the increase of the <em>unproductivity</em> of labour, and the consequence is a relative <em>overpopulation</em> which, as we have seen, is produced by the accumulation of capital; not by the increase of the <em>unproductivity</em> of labour, as the economists maintain, but by the growth of its <em>productivity.</em></p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Das Bestehen einer sogenannten Uebervölkerung, das Vorhandensein einer <em>industriellen Reservearmee</em> hemmt jedoch nicht die Entwicklung des Kapitals, sondern bildet, von einem gewissen Punkte an, eine ihrer Voraussetzungen.</p>
</div>
<div class="parallel-col-en">
<p>The existence of a so-called overpopulation, the presence of an <em>industrial reserve army,</em> does not, however, hamper the development of capital, but constitutes, from a certain point onwards, one of its preconditions.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Das Kapital ist, wie wir wissen, eine elastische Größe. Je mehr die kapitalistische Produktionsweise sich entwickelt, desto heftiger und umfangreicher werden seine periodischen Ausdehnungen und Zusammenziehungen. Die moderne Großindustrie bewegt sich, wie schon im zweiten Abschnitt angedeutet, in einem ihr eigenthümlichen Kreislauf, der sich bis 1873 in Perioden von ungefähr zehn Jahren wiederholte; mit mittlerer Lebendigkeit des Geschäftsganges hebt er an, diese wächst rasch, ein wirthschaftlicher Aufschwung tritt ein, eine kolossale plötzliche Ausdehnung der Produktion, ein Produktionsfieber – dann der Krach, Versumpfung des Geschäftslebens, bis die Märkte sich entsprechend erweitert und den Ueberschuß au Produkten aufgesogen haben, worauf eine Erholung eintritt und das alte Spiel von Neuem in vergrößertem Maßstabe beginnt.</p>
</div>
<div class="parallel-col-en">
<p>Capital is, as we know, an elastic magnitude. The more the capitalist mode of production develops, the more violent and more extensive become its periodic expansions and contractions. Modern large-scale industry moves, as already indicated in the second section, in a cycle peculiar to it, which up to 1873 repeated itself in periods of about ten years; it begins with a middling liveliness of the course of business, this grows rapidly, an economic upswing sets in, a colossal sudden expansion of production, a production fever – then the crash, the stagnation of business life, until the markets have expanded correspondingly and absorbed the surplus of products, whereupon a recovery sets in and the old game begins anew on an enlarged scale.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>So war es, als Marx sein <strong>Kapital</strong> verfaßte, das 1867 zuerst erschien. So war es, als er das <em>Nachwort</em> zu der zweiten Auflage seines <strong>Kapital</strong> schrieb (am 24. Januar 1873), in dem er erklärte, daß die allgemeine Krisis im Anmarsch sei. <a href="#ab3-kap5-n2" id="ab3-kap5-f2" name="ab3-kap5-f2">[2]</a></p>
</div>
<div class="parallel-col-en">
<p>So it was when Marx composed his <strong>Capital,</strong> which first appeared in 1867. So it was when he wrote the <em>Afterword</em> to the second edition of his <strong>Capital</strong> (on 24 January 1873), in which he declared that the general crisis was on the march. <a href="#ab3-kap5-n2" id="ab3-kap5-f2" name="ab3-kap5-f2">[2]</a></p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Wir alle wissen, wie bald und nur zu genau diese Prophezeiung zur Wahrheit geworden ist.</p>
</div>
<div class="parallel-col-en">
<p>We all know how soon and only too exactly this prophecy became truth.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Mit der Krise, die 1873 begann, schien jedoch die kapitalistische Produktionsweise in eine neue Phase getreten zu sein. Wenn sich die Produktivität der Großindustrie bis dahin so rasch entwickelte, daß sie zeitweilig schneller wuchs, als die Ausdehnung des Weltmarktes, so schien jetzt in Folge der kolossalen Fortschritte der Technik und der enormen Erweiterung des Herrschaftsgebietes der kapitalistischen Produktion – bis nach Rußland, nach Amerika, Ostindien, Australien – die Zeit gekommen zu sein, wo der Weltmarkt nur vorübergehend und ausnahmsweise im Stande war, die Produkte der Weltindustrie aufzusaugen: anstatt eines Kreislaufs von zehn Jahren, in dem mittlere Lebendigkeit des Wirthschaftslebens, fieberhafter Produktionsschwindel, Krach, Versumpfung, Wiederaufleben mit einander abwechseln, hatten wir seit 1873 die chronische Geschäftsstockung, die dauernde Versumpfung auf ökonomischem Gebiet, die erst 1889 durch eine Verbesserung des Geschäftsganges unterbrochen wurde, ein kurzes Aufflackern des Spekulationsgeistes, das bald wieder vorüberging und einer noch ärgeren Versumpfung des wirthschaftlichen Lebens Platz machte. Es schien, als sollte es zu einem bedeutenderen „wirthschaftlichen Aufschwung“ überhaupt nicht mehr kommen. Diese Annahme war jedoch irrig. Von 1895 bis 1900 hatten wir wieder eine Periode des wirthschaftlichen Ausschwungs, eines so kräftigen Aufschwungs, daß er sogar nicht wenige Optimisten zu der entgegengesetzten Annahme verführte, als sei die Zeit der Krisen überhaupt vorüber oder es seien diese im Rückgang begriffen.</p>
</div>
<div class="parallel-col-en">
<p>With the crisis that began in 1873, however, the capitalist mode of production seemed to have entered a new phase. If the productivity of large-scale industry had until then developed so rapidly that at times it grew faster than the expansion of the world market, now, as a consequence of the colossal advances of technology and the enormous extension of the domain of capitalist production – as far as Russia, America, the East Indies, Australia – the time seemed to have come when the world market was able to absorb the products of world industry only temporarily and exceptionally: instead of a cycle of ten years, in which moderate liveliness of economic life, feverish production swindle, crash, stagnation, and revival alternated with one another, we have had since 1873 the chronic stagnation of business, the enduring stagnation in the economic sphere, which was interrupted only in 1889 by an improvement in the course of business, a brief flaring-up of the spirit of speculation, which soon passed again and made way for an even worse stagnation of economic life. It seemed as though a more significant "economic upswing" would never come about at all. This assumption was, however, mistaken. From 1895 to 1900 we had once again a period of economic upswing, an upswing so vigorous that it even seduced not a few optimists into the opposite assumption, namely that the era of crises was over altogether or that these were in decline.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Diese Annahme war von vornherein unhaltbar, da ein wirthschaftlicher Aufschwung in der kapitalistischen Produktionsweise nothwendigerweise in einer Krise enden muß, die denn auch prompt eingetreten ist.</p>
</div>
<div class="parallel-col-en">
<p>This assumption was untenable from the outset, since an economic upswing under the capitalist mode of production must necessarily end in a crisis, which indeed promptly ensued.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>In diesem Zusammenhange kommt es jedoch nur auf die zeitweisen Ausdehnungen und Zusammenziehungen des Kapitals an, und solche finden während der chronischen Geschäftsstockung ebenso statt, wie in dem zehnjährigen Kreislauf von Krise und wirthschaftlicher Blüthe.</p>
</div>
<div class="parallel-col-en">
<p>In this connection, however, only the temporary expansions and contractions of capital matter, and such take place during the chronic stagnation of business just as much as in the ten-year cycle of crisis and economic prosperity.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Eine jede derartige zeitweise Ausdehnung des Kapitals erzeugt ein größeres Bedürfniß nach Arbeitskraft; wie wird dem entsprochen? Der Arbeitslohn steigt, und das hat nach der Theorie der Oekonomen eine Vermehrung der Bevölkerung zur Folge – nach zwanzig Jahren wird die Arbeiterbevölkerung zahlreich genug geworden sein, daß das Kapital die Konjunktur ausnützen kann. Aber diese dauert jedesmal nur einige Jahre, oft nur einige Monate! Zum Glück für das Kapital verhält sich die Sachlage in Wirklichkeit anders, als nach der Theorie des „ehernen Lohngesetzes.“ Die kapitalistische Produktionsweise erzeugt, wie wir gesehen haben, künstlich eine überschüssige Arbeiterbevölkerung; und diese ist die <em>Reservearmee,</em> aus der das Kapital in jedem Augenblick so viel zuschüssige Arbeiter entnehmen kann, als seinen Bedürfnissen entspricht; ohne sie wäre die so eigenthümliche stoßweise Entwicklung der kapitalistischen Großindustrie unmöglich. Wo wäre die deutsche Industrie, wenn sie Anfangs der siebziger und ebenso in der zweiten Hälfte der neunziger Jahre nicht so viele Hände gefunden hätte, die „frei“ waren und zu ihrer Verfügung standen, ganze Arbeiterarmeen, die sie auf den Eisenbahnbau werfen konnte, in neue Kohlengruben, Eisenhütten u.&nbsp;s.&nbsp;w. Diese Reservearmee ermöglicht aber nicht nur die plötzliche Ausdehnung des Kapitals, sie drückt auch auf den Lohn, und da sie kaum in den Zeiten blühendster Geschäfte völlig in Anspruch genommen wird, wirkt sie darauf hin, daß dieser selbst zur Zeit des größten Produktionslärms eine gewisse Höhe nicht zu übersteigen vermag.</p>
</div>
<div class="parallel-col-en">
<p>Each such temporary expansion of capital creates a greater need for labour-power; how is this met? Wages rise, and according to the theory of the economists this results in an increase of the population – after twenty years the working population will have become numerous enough for capital to exploit the favourable conjuncture. But this lasts each time only a few years, often only a few months! Fortunately for capital, the actual state of affairs is different from what the theory of the "iron law of wages" would have it. The capitalist mode of production, as we have seen, artificially produces a surplus working population; and this is the <em>reserve army</em> from which capital can at any moment draw as many additional workers as correspond to its needs; without it the so peculiar spasmodic development of capitalist large-scale industry would be impossible. Where would German industry be if, at the beginning of the seventies and likewise in the second half of the nineties, it had not found so many hands that were "free" and stood at its disposal, whole armies of workers whom it could throw onto railway construction, into new coal pits, ironworks, and so forth. But this reserve army not only makes possible the sudden expansion of capital, it also presses down on wages, and since it is scarcely fully called upon even in the times of most flourishing business, it works so that even at the time of the greatest production din wages cannot rise above a certain level.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Was als Auf- und Abschwanken der Bevölkerungszahl erscheint, ist in Wahrheit nur das Spiegelbild der periodischen Ausdehnung und Zusammenziehung des Kapitals. Wenn die Malthusianer von den Arbeitern verlangen, sie sollen ihre Vermehrung nach dem Grade der für sie vorhandenen Beschäftigung einrichten, so heißt das also nichts anderes, als sie sollen ihre Zahl den jeweiligen Bedürfnissen des Kapitals anpassen.</p>
</div>
<div class="parallel-col-en">
<p>What appears as an up-and-down fluctuation in the size of the population is in truth only the reflection of the periodic expansion and contraction of capital. When the Malthusians demand of the workers that they should regulate their multiplication according to the degree of employment available to them, this means nothing other than that they should adapt their numbers to the current needs of capital.</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>Der Malthusianismus beruht auf einer Verwechslung der so veränderlichen Produktionsbedürfnisse des Kapitals mit der Produktivkraft der vorhandenen Produktionsmittel; war diese Verwechslung stets absurd, so wurde sie es am offenbarsten in den letzten zwei Jahrzehnten. Wir haben seitdem auf dem flachen Lande in Europa eine Uebervölkerung aus Ueberfluß an Lebensmitteln, Uebervölkerung in Folge der amerikanischen, indischen, australischen Fleisch- und Brot-Konkurrenz!</p>
</div>
<div class="parallel-col-en">
<p>Malthusianism rests on a confusion of the so variable production needs of capital with the productive power of the existing means of production; if this confusion was always absurd, it became most manifestly so in the last two decades. Since then we have had in the flat countryside of Europe an overpopulation arising from a superabundance of means of subsistence, an overpopulation as a consequence of American, Indian, and Australian meat and bread competition!</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p>So absurd dies auch klingt, so sind doch die Forderungen des Malthusianismus nur der entsprechende Ausdruck der Stellung, welche der Arbeiter heute dem Kapital gegenüber einnimmt: er ist nur Zubehör des Kapitals; während des Produktionsprozesses wendet das Produktionsmittel ihn an, nicht er das Produktionsmittel; aber er gehört auch außerhalb der Arbeit dem Kapital, wie wir gesehen haben; wenn er konsumirt, wenn er sich erhält und fortpflanzt, so hat er es in der Weise zu thun, die den Interessen des Kapitals am besten entspricht. Sein eigenes Produkt unterjocht den Arbeiter: es macht sich nicht nur seine Arbeitskraft dienstbar, sondern alle Bethätigungen seines menschlichen Wesens.</p>
</div>
<div class="parallel-col-en">
<p>Absurd as this may sound, the demands of Malthusianism are nevertheless only the corresponding expression of the position which the worker today occupies in relation to capital: he is only an appendage of capital; during the production process the means of production employs him, not he the means of production; but he also belongs to capital outside of labour, as we have seen; when he consumes, when he maintains and reproduces himself, he must do so in the manner that best corresponds to the interests of capital. His own product subjugates the worker: it makes not only his labour-power serviceable to itself, but all the activities of his human being.</p>
</div>
</div>
</section>
<section id="notes-anmerkungen" class="level2">
<h2 class="anchored" data-anchor-id="notes-anmerkungen">Notes / Anmerkungen</h2>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="note"><a href="#ab3-kap5-f1" id="ab3-kap5-n1" name="ab3-kap5-n1">1.</a> Marx sagt:</p>
</div>
<div class="parallel-col-en">
<p class="note"><a href="#ab3-kap5-f1" id="ab3-kap5-n1" name="ab3-kap5-n1">1.</a> Marx says:</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="quoteb">„So drückt sich in der Krisenphase des industriellen Zyklus der allgemeine Fall der Waarenpreise als Steigen des relativen Geldwerths, und in der Prosperitätsphase das allgemeine Steigen der Waarenpreise als Fall des relativen Geldwerthes aus. Die sogenannte Currency-Schule schließt daher, daß bei hohen Preisen zu wenig, bei niedrigen zu viel Geld zirkulirt. Ihre Ignoranz und völlige Verkennung der Thatsachen finden würdige Parallele in den Oekonomen, welche jene Phänomene der Akkumulation dahin deuten, daß das einemal zu wenig und das anderemal zu viel Lohnarbeiter existiren.“</p>
</div>
<div class="parallel-col-en">
<p class="quoteb">"Thus in the crisis phase of the industrial cycle the general fall of commodity prices is expressed as a rise of the relative value of money, and in the prosperity phase the general rise of commodity prices as a fall of the relative value of money. The so-called currency school therefore concludes that with high prices too little, and with low prices too much money circulates. Its ignorance and complete misapprehension of the facts find a worthy parallel in the economists who interpret those phenomena of accumulation to mean that at one time too few and at another time too many wage labourers exist."</p>
</div>
</div>
<div class="parallel-container">
<div class="parallel-col-de">
<p class="note"><a href="#ab3-kap5-f2" id="ab3-kap5-n2" name="ab3-kap5-n2">2.</a> Der von uns schon im zweiten Abschnitt gekennzeichnete Dr. Stegemann bemerkt mit Schaudern mit Bezug auf diesen Satz: „<em>Marx trägt kein Bedenken</em> (!) die allgemeine Krise als nahe bevorstehend anzukündigen.“ <strong>(Preußische Jahrbücher,</strong> LVII, S.&nbsp;227) Marx spricht an der in Rede stehenden Stelle von „den Wechselfällen des <em>periodischen Zyklus,</em> den die <em>moderne Industrie</em> durchläuft und deren <em>Gipfelpunkt</em> – die allgemeine Krise.“ Deutlicher kann man wohl nicht reden. Das hindert jedoch nicht, daß der gelehrte Herr Doktor die Krise, von der die Rede, als – die <em>Revolution</em> ausfaßt. Aehnliche „Verwechslungen,“ um uns parlamentarisch auszudrücken, natürlich stets zu Gunsten der schaurigsten Auffassung – passirten nur zu vielen „Gelehrten,“ die Marx gelesen – oder auch nicht gelesen – und zitirt haben.</p>
</div>
<div class="parallel-col-en">
<p class="note"><a href="#ab3-kap5-f2" id="ab3-kap5-n2" name="ab3-kap5-n2">2.</a> Dr. Stegemann, whom we have already characterised in the second section, remarks with a shudder in reference to this sentence: "<em>Marx has no scruple</em> (!) in announcing the general crisis as imminent." <strong>(Preußische Jahrbücher,</strong> LVII, p. 227) Marx speaks in the passage in question of "the vicissitudes of the <em>periodic cycle</em> through which <em>modern industry</em> runs and whose <em>culminating point</em> – the general crisis." One can hardly speak more clearly. This does not prevent the learned Herr Doctor from construing the crisis of which the discussion is – as the <em>revolution</em>. Similar "confusions," to put it parliamentarily, naturally always in favour of the most gruesome interpretation – have befallen all too many "scholars" who have read – or also not read – and cited Marx.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dwbcampbell\.github\.io\/kautsky\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>